if(EXISTS "/mnt/c/Users/Bera/Desktop/ce103-midterm-ahmetbera-celik-enes-koy/build_linux/src/tests/hospitalsystem/hospitalsystem_tests[1]_tests.cmake")
  include("/mnt/c/Users/Bera/Desktop/ce103-midterm-ahmetbera-celik-enes-koy/build_linux/src/tests/hospitalsystem/hospitalsystem_tests[1]_tests.cmake")
else()
  add_test(hospitalsystem_tests_NOT_BUILT hospitalsystem_tests_NOT_BUILT)
endif()
